name = "Create Aero n' Stuff"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ae757cf97a52abe3a007812e7ee69b6553075cbd986494699f02ca9066ef279"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
