name = "Create Aero n' Stuff"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f94e9459560eaa7709d12dcfe551a5ac97de0138df9b5ecce2200888b04243"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
